In [2]:
import re
import numpy as np
from typing import List
import matplotlib.pyplot as plt

In [3]:
text = ["All that we are is the result of what we have thought", 
        "To be or not to be that is the question",
        "Be yourself everyone else is already taken",]

In [4]:
# separate into words
joined_text = " ".join(text).lower()
all_words = re.split(r'\s+', joined_text)
all_words

['all',
 'that',
 'we',
 'are',
 'is',
 'the',
 'result',
 'of',
 'what',
 'we',
 'have',
 'thought',
 'to',
 'be',
 'or',
 'not',
 'to',
 'be',
 'that',
 'is',
 'the',
 'question',
 'be',
 'yourself',
 'everyone',
 'else',
 'is',
 'already',
 'taken']

In [5]:
# create a vocabulary
vocab = set(all_words)
vocab

{'all',
 'already',
 'are',
 'be',
 'else',
 'everyone',
 'have',
 'is',
 'not',
 'of',
 'or',
 'question',
 'result',
 'taken',
 'that',
 'the',
 'thought',
 'to',
 'we',
 'what',
 'yourself'}

In [6]:
print(f"Number of unique words: {len(vocab)}")

Number of unique words: 21


In [7]:
# create an encoder and decoder
word2idx = {word: idx for idx, word in enumerate(vocab)} # encoder
idx2word = {idx: word for word, idx in word2idx.items()} # decoder

print(f"Encoder (word to index): {word2idx}")
print(f"Decoder (index to word): {idx2word}")

Encoder (word to index): {'yourself': 0, 'is': 1, 'result': 2, 'already': 3, 'thought': 4, 'are': 5, 'the': 6, 'else': 7, 'we': 8, 'have': 9, 'all': 10, 'or': 11, 'be': 12, 'everyone': 13, 'of': 14, 'not': 15, 'question': 16, 'taken': 17, 'to': 18, 'that': 19, 'what': 20}
Decoder (index to word): {0: 'yourself', 1: 'is', 2: 'result', 3: 'already', 4: 'thought', 5: 'are', 6: 'the', 7: 'else', 8: 'we', 9: 'have', 10: 'all', 11: 'or', 12: 'be', 13: 'everyone', 14: 'of', 15: 'not', 16: 'question', 17: 'taken', 18: 'to', 19: 'that', 20: 'what'}


In [8]:
def encoder_function(word : List[str]):
    return [word2idx.get(w, None) for w in word]

def decoder_function(idx : List[int]):
    return [idx2word.get(i, None) for i in idx]

encoder_function(["thought", "so", "to"]), decoder_function([12, 13, 90, 5])

([4, None, 18], ['be', 'everyone', None, 'are'])

In [9]:
 # select random words to create random sentences
rand_idx = np.random.choice(len(vocab), size=5, replace=False)
rand_words = [idx2word[idx] for idx in rand_idx]
print(" ".join(rand_words))

the question thought already be


In [10]:
# translate the text into numbers
text_as_int = [word2idx[word] for word in all_words]
text_as_int

[10,
 19,
 8,
 5,
 1,
 6,
 2,
 14,
 20,
 8,
 9,
 4,
 18,
 12,
 11,
 15,
 18,
 12,
 19,
 1,
 6,
 16,
 12,
 0,
 13,
 7,
 1,
 3,
 17]

In [11]:
# and numbers back to words
text_as_words = [idx2word[idx] for idx in text_as_int]
text_as_words

['all',
 'that',
 'we',
 'are',
 'is',
 'the',
 'result',
 'of',
 'what',
 'we',
 'have',
 'thought',
 'to',
 'be',
 'or',
 'not',
 'to',
 'be',
 'that',
 'is',
 'the',
 'question',
 'be',
 'yourself',
 'everyone',
 'else',
 'is',
 'already',
 'taken']

In [12]:
# what words are in the context of "to"

target_word = "to"
target_idx = word2idx[target_word]

# find the indices of the target word in the text
target_indices = np.where(np.array(text_as_int) == target_idx)[0]
print("Target indices:", target_indices)

# print the context words (1 before and 1 after)
context_size = 1
for idx in target_indices:
    context_words = text_as_words[idx - context_size : idx + context_size + 1]
    print(f"Context for '{target_word}' at index {idx}: {context_words}")

Target indices: [12 16]
Context for 'to' at index 12: ['thought', 'to', 'be']
Context for 'to' at index 16: ['not', 'to', 'be']


In [20]:
len(all_words), len(vocab)

# create a one-hot encoding for all words in the vocabulary without assuming any order
word_matrix = np.zeros((len(all_words), len(vocab)), dtype=int)
for idx, word in enumerate(all_words):
    word_idx = word2idx[word]
    word_matrix[idx, word_idx] = 1

print("One-hot encoded word matrix:")
print(f"Shape of the word matrix: {word_matrix.shape}")
print(word_matrix)

One-hot encoded word matrix:
Shape of the word matrix: (29, 21)
[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 